version: '3.8'
services:
  metabase:
    image: metabase/metabase:v0.40.5
    container_name: metabase.trade.sniper
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - metabase-data:/metabase-data
    command:
      - --log-metrics
      - --plugins-dir=/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  metabase-data:
